package net.halalaboos.mcwrapper.api.item;

import net.halalaboos.mcwrapper.api.MCWrapper;

/**
 * Every item within the 1.11.2 version of Minecraft. <br/>
 * Created by Brandon Williams on 2/21/2017.
 */
public enum Items {

	GHAST_TEAR("ghast_tear", 370),
	BOOK("book", 340),
	RECORD_WARD("record_ward", 2265),
	LEATHER("leather", 334),
	JUNGLE_DOOR("jungle_door", 429),
	SPAWN_EGG("spawn_egg", 383),
	IRON_CHESTPLATE("iron_chestplate", 307),
	CHAINMAIL_CHESTPLATE("chainmail_chestplate", 303),
	DIAMOND_PICKAXE("diamond_pickaxe", 278),
	RECORD_11("record_11", 2266),
	FERMENTED_SPIDER_EYE("fermented_spider_eye", 376),
	COOKED_CHICKEN("cooked_chicken", 366),
	MINECART("minecart", 328),
	SPLASH_POTION("splash_potion", 438),
	BUCKET("bucket", 325),
	EMERALD("emerald", 388),
	LEATHER_BOOTS("leather_boots", 301),
	IRON_INGOT("iron_ingot", 265),
	LINGERING_POTION("lingering_potion", 441),
	RABBIT("rabbit", 411),
	GLASS_BOTTLE("glass_bottle", 374),
	RECORD_CAT("record_cat", 2257),
	CLAY_BALL("clay_ball", 337),
	LEATHER_HELMET("leather_helmet", 298),
	RECORD_FAR("record_far", 2260),
	REPEATER("repeater", 356),
	NETHER_STAR("nether_star", 399),
	RECORD_WAIT("record_wait", 2267),
	FLOWER_POT("flower_pot", 390),
	GOLDEN_CARROT("golden_carrot", 396),
	BEEF("beef", 363),
	FIREWORK_CHARGE("firework_charge", 402),
	SUGAR("sugar", 353),
	FIREWORKS("fireworks", 401),
	CHICKEN("chicken", 365),
	END_CRYSTAL("end_crystal", 426),
	DIAMOND_LEGGINGS("diamond_leggings", 312),
	IRON_DOOR("iron_door", 330),
	TIPPED_ARROW("tipped_arrow", 440),
	GOLDEN_HORSE_ARMOR("golden_horse_armor", 418),
	QUARTZ("quartz", 406),
	BAKED_POTATO("baked_potato", 393),
	BRICK("brick", 336),
	DIAMOND_BOOTS("diamond_boots", 313),
	ENDER_EYE("ender_eye", 381),
	IRON_BOOTS("iron_boots", 309),
	WRITABLE_BOOK("writable_book", 386),
	DARK_OAK_BOAT("dark_oak_boat", 448),
	COOKED_FISH("cooked_fish", 350),
	FLINT("flint", 318),
	IRON_HORSE_ARMOR("iron_horse_armor", 417),
	DIAMOND_SHOVEL("diamond_shovel", 277),
	COMPARATOR("comparator", 404),
	DIAMOND_HOE("diamond_hoe", 293),
	COMMAND_BLOCK_MINECART("command_block_minecart", 422),
	SHULKER_SHELL("shulker_shell", 450),
	MUTTON("mutton", 423),
	CARROT("carrot", 391),
	STRING("string", 287),
	SPRUCE_BOAT("spruce_boat", 444),
	WOODEN_AXE("wooden_axe", 271),
	NETHERBRICK("netherbrick", 405),
	GOLD_INGOT("gold_ingot", 266),
	POTATO("potato", 392),
	MELON_SEEDS("melon_seeds", 362),
	COAL("coal", 263),
	NETHER_WART("nether_wart", 372),
	PAINTING("painting", 321),
	BREAD("bread", 297),
	DARK_OAK_DOOR("dark_oak_door", 431),
	FISHING_ROD("fishing_rod", 346),
	CHEST_MINECART("chest_minecart", 342),
	BLAZE_POWDER("blaze_powder", 377),
	CHAINMAIL_BOOTS("chainmail_boots", 305),
	PUMPKIN_PIE("pumpkin_pie", 400),
	ROTTEN_FLESH("rotten_flesh", 367),
	ENCHANTED_BOOK("enchanted_book", 403),
	CAKE("cake", 354),
	COOKIE("cookie", 357),
	COOKED_MUTTON("cooked_mutton", 424),
	SPRUCE_DOOR("spruce_door", 427),
	RABBIT_FOOT("rabbit_foot", 414),
	GOLDEN_BOOTS("golden_boots", 317),
	COMPASS("compass", 345),
	COOKED_RABBIT("cooked_rabbit", 412),
	RECORD_13("record_13", 2256),
	LEATHER_CHESTPLATE("leather_chestplate", 299),
	ACACIA_BOAT("acacia_boat", 447),
	MILK_BUCKET("milk_bucket", 335),
	RECORD_STAL("record_stal", 2263),
	SADDLE("saddle", 329),
	LAVA_BUCKET("lava_bucket", 327),
	WATER_BUCKET("water_bucket", 326),
	POTION("potion", 373),
	REDSTONE("redstone", 331),
	GOLDEN_LEGGINGS("golden_leggings", 316),
	ITEM_FRAME("item_frame", 389),
	SPECTRAL_ARROW("spectral_arrow", 439),
	REEDS("reeds", 338),
	EXPERIENCE_BOTTLE("experience_bottle", 384),
	WOODEN_SHOVEL("wooden_shovel", 269),
	BOW("bow", 261),
	IRON_HOE("iron_hoe", 292),
	DIAMOND_HELMET("diamond_helmet", 310),
	CHORUS_FRUIT_POPPED("chorus_fruit_popped", 433),
	SNOWBALL("snowball", 332),
	ACACIA_DOOR("acacia_door", 430),
	BEETROOT_SEEDS("beetroot_seeds", 435),
	TNT_MINECART("tnt_minecart", 407),
	BIRCH_BOAT("birch_boat", 445),
	RABBIT_STEW("rabbit_stew", 413),
	MAP("map", 395),
	FILLED_MAP("filled_map", 358),
	FISH("fish", 349),
	GOLDEN_CHESTPLATE("golden_chestplate", 315),
	COOKED_PORKCHOP("cooked_porkchop", 320),
	BOWL("bowl", 281),
	WOODEN_SWORD("wooden_sword", 268),
	GUNPOWDER("gunpowder", 289),
	SPIDER_EYE("spider_eye", 375),
	GOLDEN_SHOVEL("golden_shovel", 284),
	DIAMOND_AXE("diamond_axe", 279),
	STONE_PICKAXE("stone_pickaxe", 274),
	ARROW("arrow", 262),
	SHIELD("shield", 442),
	IRON_LEGGINGS("iron_leggings", 308),
	BIRCH_DOOR("birch_door", 428),
	GOLD_NUGGET("gold_nugget", 371),
	RECORD_BLOCKS("record_blocks", 2258),
	MELON("melon", 360),
	IRON_SHOVEL("iron_shovel", 256),
	ARMOR_STAND("armor_stand", 416),
	FEATHER("feather", 288),
	IRON_NUGGET("iron_nugget", 452),
	RECORD_MELLOHI("record_mellohi", 2262),
	MAGMA_CREAM("magma_cream", 378),
	BOAT("boat", 333),
	JUNGLE_BOAT("jungle_boat", 446),
	ENDER_PEARL("ender_pearl", 368),
	BEETROOT("beetroot", 434),
	WOODEN_DOOR("wooden_door", 324),
	RABBIT_HIDE("rabbit_hide", 415),
	WRITTEN_BOOK("written_book", 387),
	APPLE("apple", 260),
	SPECKLED_MELON("speckled_melon", 382),
	BREWING_STAND("brewing_stand", 379),
	RECORD_STRAD("record_strad", 2264),
	PUMPKIN_SEEDS("pumpkin_seeds", 361),
	DIAMOND_HORSE_ARMOR("diamond_horse_armor", 419),
	CHAINMAIL_HELMET("chainmail_helmet", 302),
	DIAMOND("diamond", 264),
	PRISMARINE_SHARD("prismarine_shard", 409),
	GOLDEN_APPLE("golden_apple", 322),
	CARROT_ON_A_STICK("carrot_on_a_stick", 398),
	SHEARS("shears", 359),
	SKULL("skull", 397),
	STONE_SHOVEL("stone_shovel", 273),
	CHORUS_FRUIT("chorus_fruit", 432),
	EGG("egg", 344),
	RECORD_MALL("record_mall", 2261),
	COOKED_BEEF("cooked_beef", 364),
	ELYTRA("elytra", 443),
	LEATHER_LEGGINGS("leather_leggings", 300),
	GOLDEN_PICKAXE("golden_pickaxe", 285),
	DIAMOND_SWORD("diamond_sword", 276),
	IRON_SWORD("iron_sword", 267),
	IRON_AXE("iron_axe", 258),
	CLOCK("clock", 347),
	IRON_PICKAXE("iron_pickaxe", 257),
	BLAZE_ROD("blaze_rod", 369),
	GOLDEN_HELMET("golden_helmet", 314),
	FURNACE_MINECART("furnace_minecart", 343),
	CAULDRON("cauldron", 380),
	FIRE_CHARGE("fire_charge", 385),
	LEAD("lead", 420),
	GOLDEN_HOE("golden_hoe", 294),
	STONE_HOE("stone_hoe", 291),
	STONE_SWORD("stone_sword", 272),
	BED("bed", 355),
	MUSHROOM_STEW("mushroom_stew", 282),
	DYE("dye", 351),
	GLOWSTONE_DUST("glowstone_dust", 348),
	IRON_HELMET("iron_helmet", 306),
	STICK("stick", 280),
	CHAINMAIL_LEGGINGS("chainmail_leggings", 304),
	POISONOUS_POTATO("poisonous_potato", 394),
	BONE("bone", 352),
	HOPPER_MINECART("hopper_minecart", 408),
	DIAMOND_CHESTPLATE("diamond_chestplate", 311),
	FLINT_AND_STEEL("flint_and_steel", 259),
	TOTEM_OF_UNDYING("totem_of_undying", 449),
	WOODEN_HOE("wooden_hoe", 290),
	DRAGON_BREATH("dragon_breath", 437),
	SLIME_BALL("slime_ball", 341),
	WHEAT("wheat", 296),
	AIR("air", 0),
	SIGN("sign", 323),
	PRISMARINE_CRYSTALS("prismarine_crystals", 410),
	PAPER("paper", 339),
	RECORD_CHIRP("record_chirp", 2259),
	BEETROOT_SOUP("beetroot_soup", 436),
	WOODEN_PICKAXE("wooden_pickaxe", 270),
	WHEAT_SEEDS("wheat_seeds", 295),
	PORKCHOP("porkchop", 319),
	GOLDEN_AXE("golden_axe", 286),
	GOLDEN_SWORD("golden_sword", 283),
	STONE_AXE("stone_axe", 275),
	NAME_TAG("name_tag", 421);

    private final int ID;
	private final String NAME;

    Items(String name, int id) {
    	this.NAME = name;
        this.ID = id;
    }

    public static Item getItem(int id) {
        return MCWrapper.getAdapter().getItemRegistry().getItem(id);
    }

    public Item getItem() {
    	return getItem(ID);
	}

	public int getId() {
		return ID;
	}

	public String getName() {
		return NAME;
	}
}
